workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS (unsigned)
        script: |
          cd ios
          pod install
          cd ..
          flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../ipa/emk_app.ipa Payload/
    artifacts:
      - build/ios/ipa/*.ipa
