name: iOS Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons

      - name: Install Apple Private Key
        env:
          PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        run: |
          mkdir -p ~/.private_keys
          echo "$PRIVATE_KEY" > ~/.private_keys/AuthKey_$KEY_ID.p8

      - name: Build and Sign IPA
        run: |
          flutter build ipa --release --no-codesign

      - name: Upload to App Store Connect
        env:
          KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          xcrun altool --upload-app --type ios --file build/ios/ipa/*.ipa --apiKey "$KEY_ID" --apiIssuer "$ISSUER_ID"
